# Generated by Django 4.1.5 on 2023-11-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ForeignKey(default=[], on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
