# Generated by Django 4.1.5 on 2023-11-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
