# Generated by Django 4.1.5 on 2023-11-20 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
